      integer natcdimhits
      PARAMETER (natcdimhits=15)

      real*8 IatcCounter,IatcXin,
     &   IatcYin,IatcZin,IatcXout,IatcYout,IatcZout,
     &   IatcIa_ch,IatcIa_sc,IatcIsh_ch,IatcIsh_sc
     &   IatcItef_ch,IatcItef_sc,IatcNAME,IatcNLEVEL
      parameter (IatcCounter=1,IatcXin=2,IatcYin=3,
     &   IatcZin=4,IatcXout=5,IatcYout=6,IatcZout=7,
     &   IatcIa_ch=8,IatcIa_sc=9,IatcIsh_ch=10,
     &   IatcIsh_sc=11,IatcItef_ch=12,IatcItef_sc=13,
     &   IatcNAME=14,IatcNLEVEL=15)

