      integer iatc_length       ! length of data
      integer iatc_CNT  	! ATC counter number
      integer ratc_X1
      integer ratc_Y1		! entry point coordinates
      integer ratc_Z1
      integer ratc_X2
      integer ratc_Y2		! exit point coordinates
      integer ratc_Z2
      integer ratc_Ia_ch
      integer ratc_Ia_sc
      integer ratc_Ish_ch
      integer ratc_Ish_sc
      integer ratc_Itef_ch
      integer ratc_Itef_sc
      integer ratc_I_NAME
      integer ratc_I_NLEVEL
      parameter (iatc_CNT=1)
      parameter (ratc_X1=2)
      parameter (ratc_Y1=3)
      parameter (ratc_Z1=4)
      parameter (ratc_X2=5)
      parameter (ratc_Y2=6)
      parameter (ratc_Z2=7)
      parameter (ratc_Ia_ch=8)
      parameter (ratc_Ia_sc=9)
      parameter (ratc_Ish_ch=10)
      parameter (ratc_Ish_sc=11)
      parameter (ratc_Itef_ch=12)
      parameter (ratc_Itef_sc=13)
      parameter (ratc_I_NAME=14)
      parameter (ratc_I_NLEVEL=15)
      parameter (iatc_length=15)

