      integer ndimhits
      PARAMETER (ndimhits=23)
      integer IndXin,IndYin,IndZin,IndXout,IndYout,IndZout,
     &   IndTOF,IndAmp,IndPXin,IndPYin,IndPZin,IndPXout,
     &   IndPYout,IndPZout,IndTrack,IndCHARGE,IndMASS,IndR,IndLength, 
     &   IndPpIn,IndPpOut,IndEin,IndEout
      parameter (IndXin=1,IndYin=2,IndZin=3,IndXout=4,IndYout=5,
     &    IndZout=6,IndTOF=7,IndAmp=8,
     &    IndPXin=9,IndPYin=10,IndPZin=11,IndPXout=12,
     $    IndPYout=13,IndPZout=14,IndTrack=15,IndCHARGE=16,IndMASS=17,
     $    IndR=18,IndLength=19,IndPpIn=20,IndPpOut=21,
     $    IndEin=22,IndEout=23)
     
