      integer ntofdimhits
      PARAMETER (ntofdimhits=21)
      integer ItofXm,
     &   ItofYm,ItofZm,ItofXout,ItofYout,ItofZout,
     &   ItofTime,ItofEloss,ItofXin,ItofYin,ItofZin,
     &   ItofPXin,ItofPYin,ItofPZin,ItofPin,
     &   ItofTrack,ItofCHARGE,ItofMASS,ItofParticle,
     &   ItofCounter,ItofEpartin
      parameter (ItofXm=1,
     &   ItofYm=2,ItofZm=3,ItofXout=4,ItofYout=5,ItofZout=6,
     &   ItofTime=7,ItofEloss=8,ItofXin=9,ItofYin=10,ItofZin=11,
     &   ItofPXin=12,ItofPYin=13,ItofPZin=14,ItofPin=15,
     &   ItofTrack=16,ItofCHARGE=17,ItofMASS=18,ItofParticle=19,
     &   ItofCounter=20,ItofEpartin=21)

      
