      integer nvddimhits
      PARAMETER (nvddimhits=24)
      integer IvdXTB,IvdYTB,
     &   IvdXin,IvdYin,IvdZin,IvdXout,IvdYout,IvdZout,
     &   IvdAmp,IvdPXin,IvdPYin,IvdPZin,IvdPXout,
     &   IvdPYout,IvdPZout,IvdTrack,IvdCHARGE,IvdMASS,IvdR,
     &   IvdLen,IvdPpIn,IvdPpOut,IvdEin,IvdEout
      parameter (IvdXTB=1,IvdYTB=2,
     &    IvdXin=3,IvdYin=4,IvdZin=5,
     &    IvdXout=6,IvdYout=7,IvdZout=8,
     &    IvdAmp=9,IvdPXin=10,IvdPYin=11,IvdPZin=12,IvdPXout=13,
     $    IvdPYout=14,IvdPZout=15,IvdTrack=16,IvdCHARGE=17,IvdMASS=18,
     $    IvdR=19,IvdLen=20,IvdPpIn=21,IvdPpOut=22,
     $    IvdEin=23,IvdEout=24)
      
